[versions]
kotlin = "2.4.20"
kotlinx-serialization = "1.11.0"
jna = "5.19.1"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
